# Generated by Django 5.1.2 on 2024-10-23 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='tanggal_akhir_berlaku',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
