# Generated by Django 5.1.2 on 2024-10-24 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_promo_tanggal_akhir_berlaku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='kode',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='promo',
            name='nama',
            field=models.CharField(max_length=20),
        ),
    ]
