# Generated by Django 5.1.2 on 2024-10-25 16:33

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, default='/images/default.png', null=True, upload_to='images/')),
                ('category', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=511)),
            ],
        ),
    ]
