# Generated by Django 5.1.2 on 2024-10-27 15:16

from django.core.management import call_command
from django.db import migrations


def load_fixtures(apps, schema_editor):
    call_command("loaddata", "products.json")


class Migration(migrations.Migration):

    dependencies = [
        ("adminview", "0003_alter_product_date_created"),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
    ]
