# Generated by Django 5.1.2 on 2024-10-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyEntry',
        ),
    ]
