# Generated by Django 5.1.2 on 2024-10-24 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_delete_replyentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewentry',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
