# Generated by Django 5.1.2 on 2024-10-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviewentry_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewentry',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewentry',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
