# Generated by Django 5.1.2 on 2024-10-27 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0003_alter_product_date_created'),
        ('review', '0005_alter_reviewentry_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminview.product'),
        ),
    ]
