# Generated by Django 5.1.2 on 2024-10-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_reviewentry_date_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewentry',
            name='date_update',
        ),
    ]
