# Generated by Django 5.1.2 on 2024-10-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_remove_reviewentry_date_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewentry',
            old_name='description',
            new_name='deskripsi',
        ),
    ]
