# Generated by Django 5.1.2 on 2024-10-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='img/default.png', upload_to='img/'),
        ),
    ]
