# Generated by Django 5.1.2 on 2024-10-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_remove_product_shop_alter_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
