# Generated by Django 5.1.2 on 2024-10-22 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_id_alter_cartproduct_id_alter_product_id'),
        ('display', '0003_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='display.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
