# Generated by Django 5.1.2 on 2024-10-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0001_initial'),
        ('cart', '0003_alter_cartproduct_product_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='adminview.product'),
        ),
    ]
