# Generated by Django 5.1.2 on 2024-10-27 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartproduct_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
