# Generated by Django 5.1.2 on 2024-10-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartproduct_options_cartproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={},
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='updated_at',
        ),
    ]
